name: DEV

on: push

env:
    REGISTRY: ghcr.io/${{ github.repository }}
    REGISTRY_HOST: ghcr.io
    REGISTRY_USERNAME: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
    analyze:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   name: Docker login
                uses: docker/login-action@v3
                with:
                    registry: ${{ env.REGISTRY_HOST }}
                    username: ${{ env.REGISTRY_USERNAME }}
                    password: ${{ env.REGISTRY_PASSWORD }}

            -   name: Init
                run: make init

            -   name: Lint
                run: make lint

            -   name: Analyze
                run: make analyze

            -   name: Test
                run: make test

            -   name: Bench
                run: make bench

            -   name: Down
                run: make docker-down-clear
